name: Test Code Before Merging

on:
  # Trigger on pull requests targeting the main or Staging branches
  pull_request:
    branches:
      - main
      - Staging

  # Trigger on pushes to the main or Staging branches
  push:
    branches:
      - main
      - Staging

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Next.js app
      - name: Build Next.js application
        run: npm run build
        env:
          NODE_ENV: test
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GH_OA_ID: ${{ secrets.GH_OA_ID }}
          GH_OA_SECRET: ${{ secrets.GH_OA_SECRET }}

      # Step 5: Start the Next.js application
      - name: Start Next.js application
        run: npm start &
        env:
          NODE_ENV: test
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GH_OA_ID: ${{ secrets.GH_OA_ID }}
          GH_OA_SECRET: ${{ secrets.GH_OA_SECRET }}

      # Step 6: Wait for server to be ready
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      # Step 7: Run unit tests
      - name: Run Unit Tests
        run: npm test

      # Step 8: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run


