name: Test Code Before Merging

on:
  pull_request:
    branches:
      - main # Run workflow for pull requests targeting the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Next.js app
      - name: Build Next.js application
        run: npm run build

      # Step 5: Start the Next.js application
      - name: Start Next.js application
        run: npm start & # Running in the background
        env:
          NODE_ENV: test

      # Step 6: Wait for Next.js server to be ready
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      # Step 7: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run

